version: '3.4'

services:

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: izeem-backend-container
    image: izeem-backend-image:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - database

    ports:
      - 8989:80
      - 4141:443
    networks:
      - db_bridge

  database:
    build: 
      context: .
      dockerfile: ./apps/postgres/Dockerfile
    container_name: izeem-database-container
    hostname: izeem-database-host
    image: izeem-database-image
    restart: always
    ports:
      - 5431:5432
    networks:
      - db_bridge
    
networks:
  db_bridge:
    driver: bridge